ci: update workflows for check epub file

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -96,6 +96,7 @@ jobs:
         mdbook --version
         aspell --version
         shellcheck --version
+        mdbook-epub --version
     - name: Shellcheck
       run: find . -name '*.sh' -print0 | xargs -0 shellcheck
     - name: Spellcheck
@@ -104,6 +105,10 @@ jobs:
       run: |
         mdbook build
         cargo run --bin lfp src
+    - name: Run epub backend
+      run: mdbook-epub --standalone true
+    - name: Validate exist epub file
+      run: test -e book/*.epub || test -e book/epub/* || echo "Not found EPUB file."
     - name: Validate references
       run: bash ci/validate.sh
     - name: Check for broken links
