ci: generate epub for cloudflare preview

diff --git a/.github/workflows/pr-preview.yml b/.github/workflows/pr-preview.yml
--- a/.github/workflows/pr-preview.yml
+++ b/.github/workflows/pr-preview.yml
@@ -39,7 +39,7 @@ jobs:
       BRANCH_NAME: preview-${{ github.head_ref }}
       ACTION_RUN: ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}
     steps:
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@v4
         with:
           submodules: "recursive"
           ref: ${{ github.event.pull_request.head.ref }}
@@ -59,7 +59,7 @@ jobs:
             ## ⚡ Cloudflare Pages Deployment
             | Name | Status | Preview |
             | :--- | :----- | :------ |
-            | ${{env.BRANCH_NAME}}     |  🔨 Building ([Logs](${env.ACTION_RUN}))  | waiting... |
+            | ${{env.BRANCH_NAME}}     |  🔨 Building ([Logs](${{env.ACTION_RUN}}))  | waiting... |
 
       # Build Rust Page
       - name: Install mdbook
@@ -68,8 +68,15 @@ jobs:
           curl -sSL https://github.com/RustLangES/mdBook/releases/download/v0.4.36-localization-v0.6/mdbook-v0.4.36-localization-v0.6-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=bin
           curl -sSL https://github.com/catppuccin/mdBook/releases/download/v0.1.1/mdbook-catppuccin-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=bin
           echo "$(pwd)/bin" >> ${GITHUB_PATH}
+      - name: Install mdbook-epub backend
+        run: |
+          cargo install mdbook-epub --root .
       - name: Build with mdBook
         run: mdbook build
+      - name: Run epub backend
+        run: mdbook-epub --standalone
+      - name: Validate exist epub file
+        run: test -e book/*.epub || test -e book/epub/* || echo "Not found EPUB file."
 
       # Deploy
       - name: Deploy
@@ -78,7 +85,7 @@ jobs:
         with:
           apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
           accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
-          command: pages deploy ./book --project-name=rust-book --branch="${ env.BRANCH_NAME }"
+          command: pages deploy ./book --project-name=rust-book --branch="${{ env.BRANCH_NAME }}"
 
       - name: Create comment
         uses: peter-evans/create-or-update-comment@v4
@@ -113,7 +120,7 @@ jobs:
   #       with:
   #         apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
   #         accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
-  #         command: pages --project-name=homepage --branch="${ env.BRANCH_NAME }"
+  #         command: pages --project-name=homepage --branch="${{ env.BRANCH_NAME }}"
 
   #     - name: Create comment
   #       uses: peter-evans/create-or-update-comment@v4
